server:
  port: 8088
  servlet:
    context-path: /

#表示该配置直接为Spring容器负责处理
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sduty_test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      connectionProperties: druid.stat.mergeSql=true

mybatis:  #mybatyis的配置
  configuration:
    default-fetch-size: 500
    default-statement-timeout: 20
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml   #指定mapper的配置文件的路径是mapper文件夹下的所有 xml文件。
